<!DOCTYPE html>
<!--
 * OpenBoleto - Geração de boletos bancários em PHP
 *
 * LICENSE: The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify,
 * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies
 * or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->
<html>
<head>
<meta http-equiv="Content-Type" content="text/html" charset="utf-8">
<style type="text/css">
.ti {font: 20px Arial, Helvetica, sans-serif}
</style>
</head>
<body>
<style>
<?php include $resource_path . '/css/styles.css' ?>
@media screen,print {

/* *** TIPOGRAFIA BASICA *** */

* {
	font-family: Arial;
	font-size: 12px;
	margin: 0;
	padding: 0;
}

.notice {
	color: red;
}


/* *** LINHAS GERAIS *** */

#container {
	width: 666px;
	margin: 0px auto;
	padding-bottom: 30px;
}

#instructions {
	margin: 0;
	padding: 0 0 20px 0;
}

#boleto {
	width: 666px;
	margin: 0;
	padding: 0;
}


/* *** CABECALHO *** */

#instr_header {
	background: url('https://otimize-edoc.s3.amazonaws.com/edoc_196/logo_ciga.png') no-repeat top left;
	padding-left: 160px;
	height: 65px;
	background-size: 17%;
}

#instr_header h1 {
	font-size: 16px;
	margin: 5px 0px;
}

#instr_header address {
	font-style: normal;
}

#instr_content {

}

#instr_content h2 {
	font-size: 10px;
	font-weight: bold;
}

#instr_content p {
	font-size: 10px;
	margin: 4px 0px;
}

#instr_content ol {
	font-size: 10px;
	margin: 5px 0;
}

#instr_content ol li {
	font-size: 10px;
	text-indent: 10px;
	margin: 2px 0px;
	list-style-position: inside;
}

#instr_content ol li p {
	font-size: 10px;
	padding-bottom: 4px;
}


/* *** BOLETO *** */

#boleto .cut {
	width: 666px;
	margin: 0px auto;
	border-bottom: 1px #000 dashed;
}

#boleto .cut p {
	margin: 0 0 5px 0;
	padding: 0px;
	font-family: 'Arial Narrow';
	font-size: 9px;
	color: #000;
}

table.header {
	width: 666px;
	height: 38px;
	margin-top: 20px;
	margin-bottom: 10px;
	border-bottom: 2px #000 solid;
	
}


table.header div.field_cod_banco {
	width: 60px;
	height: 19px;
  margin-left: 5px;
	padding-top: 3px;
	text-align: center;
	font-size: 14px;
	font-weight: bold;
	color: #000;
	border-right: 2px solid #000;
	border-left: 2px solid #000;
}

table.header td.linha_digitavel {
	width: 464px;
	text-align: right;
	font: bold 15.5px Arial; 
	color: #000
}

table.line {
	margin-bottom: 3px;
	padding-bottom: 1px;
	border-bottom: 1px black solid;
}

table.line tr.titulos td {
	height: 13px;
	font-family: 'Arial Narrow';
	font-size: 11px;
	color: #000;
	border-left: 5px #ffe000 solid;
	padding-left: 2px;
}

table.line tr.campos td {
	height: 12px;
	font-size: 10px;
	color: black;
	border-left: 5px #ffe000 solid;
	padding-left: 2px;
}

table.line td p {
	font-size: 10px;
}


table.line tr.campos td.ag_cod_cedente,
table.line tr.campos td.nosso_numero,
table.line tr.campos td.valor_doc,
table.line tr.campos td.vencimento2,
table.line tr.campos td.ag_cod_cedente2,
table.line tr.campos td.nosso_numero2,
table.line tr.campos td.xvalor,
table.line tr.campos td.valor_doc2
{
	text-align: right;
}

table.line tr.campos td.especie,
table.line tr.campos td.qtd,
table.line tr.campos td.vencimento,
table.line tr.campos td.especie_doc,
table.line tr.campos td.aceite,
table.line tr.campos td.carteira,
table.line tr.campos td.especie2,
table.line tr.campos td.qtd2
{
	text-align: center;
}

table.line td.last_line {
	vertical-align: top;
	height: 25px;
}

table.line td.last_line table.line {
	margin-bottom: -5px;
	border: 0 white none;
}

td.last_line table.line td.instrucoes {
	border-left: 0 white none;
	padding-left: 5px;
	padding-bottom: 0;
	margin-bottom: 0;
	height: 20px;
	vertical-align: top;
}

table.line td.cedente {
	width: 298px;
}

table.line td.valor_cobrado2 {
	padding-bottom: 0;
	margin-bottom: 0;
}


table.line td.ag_cod_cedente {
	width: 126px;
}

table.line td.especie {
	width: 35px;
}

table.line td.qtd {
	width: 53px;
}

table.line td.nosso_numero {
	/* width: 120px; */
	width: 115px;
	padding-right: 5px;
}

table.line td.num_doc {
	width: 113px;
}

table.line td.contrato {
	width: 72px;
}

table.line td.cpf_cei_cnpj {
	width: 132px;
}

table.line td.vencimento {
	width: 134px;
}

table.line td.valor_doc {
	/* width: 180px; */
	width: 175px;
	padding-right: 5px;
}

table.line td.desconto {
	width: 113px;
}

table.line td.outras_deducoes {
	width: 112px;
}

table.line td.mora_multa {
	width: 113px;
}

table.line td.outros_acrescimos {
	width: 113px;
}

table.line td.valor_cobrado {
	/* width: 180px; */
	width: 175px;
	padding-right: 5px;
	background-color: #ffc ;
}

table.line td.sacado {
	width: 659px;
}

table.line td.local_pagto {
	width: 472px;
}

table.line td.vencimento2 {
	/* width: 180px; */
	width: 175px;
	padding-right: 5px;
	background-color: #ffc;
}

table.line td.cedente2 {
	width: 472px;
}

table.line td.ag_cod_cedente2 {
	/* width: 180px; */
	width: 175px;
	padding-right: 5px;
}

table.line td.data_doc {
	width: 93px;
}

table.line td.num_doc2 {
	width: 173px;
}

table.line td.especie_doc {
	width: 72px;
}

table.line td.aceite {
	width: 34px;
}

table.line td.data_process {
	width: 72px;
}

table.line td.nosso_numero2 {
	/* width: 180px; */
	width: 175px;
	padding-right: 5px;
}

table.line td.reservado {
	width: 93px;
	background-color: #ffc;
}

table.line td.carteira {
	width: 93px;
}

table.line td.especie2 {
	width: 53px;
}

table.line td.qtd2 {
	width: 133px;
}

table.line td.xvalor {
	/* width: 72px; */
	width: 67px;
	padding-right: 5px;
}

table.line td.valor_doc2 {
	/* width: 180px; */
	width: 175px;
	padding-right: 5px;
}
table.line td.instrucoes {
	width: 475px;
}

table.line td.desconto2 {
	/* width: 180px; */
	width: 175px;
	padding-right: 5px;
}

table.line td.outras_deducoes2 {
	/* width: 180px; */
	width: 175px;
	padding-right: 5px;
}

table.line td.mora_multa2 {
	/* width: 180px; */
	width: 175px;
	padding-right: 5px;
}

table.line td.outros_acrescimos2 {
	/* width: 180px; */
	width: 175px;
	padding-right: 5px;
}

table.line td.valor_cobrado2 {
	/* width: 180px; */
	width: 175px;
	padding-right: 5px;
	background-color: #ffc ;
}

table.line td.sacado2 {
	width: 659px;
}

table.line td.sacador_avalista {
	width: 659px;
}

table.line tr.campos td.sacador_avalista {
	width: 472px;
}

table.line td.cod_baixa {
	color: #000;
	width: 180px;
}




div.footer {
	margin-bottom: 30px;
}

div.footer p {
	width: 88px;
	margin: 0;
	padding: 0;
	padding-left: 525px;
	font-family: 'Arial Narro';
	font-size: 9px;
	color: #000;
}


div.barcode {
	width: 666px;
	margin-bottom: 20px;
}

}



@media print {

#instructions {
	height: 1px;
	visibility: hidden;
	overflow: hidden;
}

}

</style>




<div id="container">

	<div class="noprint info">
            <h2>Instruções de Impressão</h2>
            <ul>
                <li>Imprima em impressora jato de tinta (ink jet) ou laser em qualidade normal ou alta (Não use modo econômico).</li>
                <li>Utilize folha A4 (210 x 297 mm) ou Carta (216 x 279 mm) e margens mínimas à esquerda e à direita do formulário.</li>
                <li>Corte na linha indicada. Não rasure, risque, fure ou dobre a região onde se encontra o código de barras.</li>
                <li>Caso não apareça o código de barras no final, pressione F5 para atualizar esta tela.</li>
                <li>Caso tenha problemas ao imprimir, copie a sequencia numérica abaixo e pague no caixa eletrônico ou no internet banking:</li>
            </ul>
            </br>
            <span class="header"><strong>Linha Digitável: <?php echo $linha_digitavel; ?></strong></span>
            <?php if ($valor_documento) : ?></br><span class="header"><strong>Valor: R$ <?php echo $valor_documento; ?></strong></span><?php endif ?>
            <?php if ($pagamento_minimo) : ?><span class="header">Pagamento mínimo: R$ <?php echo $pagamento_minimo; ?></span><?php endif ?>
            </br>
        </div>
		
<!--        <div class="info-empresa">
            <?php // if ($logotipo) : ?>
            <div style="display: inline-block;">
                <img alt="logotipo" src="<?php // echo $logotipo; ?>" />
            </div>
            <?php // endif ?>
            <div style="display: inline-block; vertical-align: super;">
                <div><strong><?php // echo $cedente; ?></strong></div>
                <div><?php // echo $cedente_cpf_cnpj; ?></div>
                <div><?php // echo $cedente_endereco1; ?></div>
                <div><?php // echo $cedente_endereco2; ?></div>
            </div>
        </div>            -->
		<!--<div id="instr_content">-->
			<!--<br><br>-->
						
						
		<!--</div>	 id="instr_content" -->
	<!--</div>	 id="instructions" -->
        </br>
	<div id="boleto">
		<div class="cut">
			<p>Corte na linha pontilhada</p>
		</div>
    <table cellspacing="0" cellpadding="0" width="666" border="0"><tbody><tr><td class="ct" width="666"><div align="right"><b class="cp">Recibo
do Sacado</b></div></td></tr></tbody></table>
		<table class="header" border="0" cellspacing="0" cellpadding="0">
		<tbody>
		<tr>
			<td width="150">
                            <img src="<?php echo $logo_banco; ?>" alt="logotipo do banco">
                        </td>
			<td width="50">
        <div class="field_cod_banco"><?php echo $codigo_banco_com_dv ?></div>
			</td>
			<td class="linha_digitavel"><?php echo $linha_digitavel ?></td>
		</tr>
		</tbody>
		</table>

		<table class="line" cellspacing="0" cellpadding="0">
		<tbody>
		<tr class="titulos">
			<td class="cedente">Cedente</td>
			<td class="ag_cod_cedente">Agência / Código do Cedente</td>
			<td class="especie">Espécie</td>
			<td class="qtd">Quantidade</td>
			<td class="nosso_numero">Nosso número</td>
		</tr>

		<tr class="campos">
			<td class="cedente"><?php echo $cedente; ?></td>
			<td class="ag_cod_cedente"><?php echo $agencia_codigo_cedente ?></td>
			<td class="especie"><?php echo $especie ?></td>
			<td class="qtd"><?php echo $quantidade ?></td>
			<td class="nosso_numero"><?php echo $nosso_numero ?></td>
		</tr>
		</tbody>
		</table>

		<table class="line" cellspacing="0" cellpadding="0">
		<tbody>
		<tr class="titulos">
			<td class="num_doc">Nº do documento</td>
			<td class="cpf_cei_cnpj">CPF/CEI/CNPJ</td>
			<td class="vencmento">Vencimento</td>
			<td class="valor_doc">Valor documento</td>
		</tr>
		<tr class="campos">
			<td class="num_doc"><?php echo $numero_documento ?></td>
			<td class="cpf_cei_cnpj"><?php echo $cedente_cpf_cnpj ?></td>
			<td class="vencimento"><?php echo $data_vencimento ?></td>
			<td class="valor_doc"><?php echo $valor_documento ?></td>
		</tr>
      </tbody>
      </table>

		<table class="line" cellspacing="0" cellpadding="0">
		<tbody>
		<tr class="titulos">
			<td class="desconto">(-) Desconto / Abatimento</td>
			<td class="outras_deducoes">(-) Outras deduções</td>
			<td class="mora_multa">(+) Mora / Multa</td>
			<td class="outros_acrescimos">(+) Outros acréscimos</td>
			<td class="valor_cobrado">(=) Valor cobrado</td>
		</tr>
		<tr class="campos">
			<td class="desconto"><?php echo $desconto_abatimento ?></td>
			<td class="outras_deducoes"><?php echo $outras_deducoes ?></td>
			<td class="mora_multa"><?php echo $mora_multa ?></td>
			<td class="outros_acrescimos"><?php echo $outros_acrescimos ?></td>
			<td class="valor_cobrado" align="right"><strong><?php echo $valor_cobrado ?></strong></td>
		</tr>
		</tbody>
		</table>

      
		<table class="line" cellspacing="0" cellpadding="0">
		<tbody>
		<tr class="titulos">
			<td class="sacado">Sacado</td>
		</tr>
		<tr class="campos">
			<td class="sacado"><?php echo $sacado ?> / <?php echo $sacado_documento ?></td>
		</tr>
		</tbody>
		</table>
		
		<div class="footer">
			<p>Autenticação mecânica</p>
		</div>

		
		
		<div class="cut">
			<p>Corte na linha pontilhada</p>
		</div>


		<table class="header" border="0" cellspacing="0" cellpadding="0">
		<tbody>
		<tr>
			<td width="150"><img src="<?php echo $logo_banco; ?>" alt="logotipo do banco"></td>
			<td width="50">
        <div class="field_cod_banco"><?php echo $codigo_banco_com_dv ?></div>
			</td>
			<td class="linha_digitavel"><?php echo $linha_digitavel ?></td>
		</tr>
		</tbody>
		</table>

		<table class="line" cellspacing="0" cellpadding="0">
		<tbody>
		<tr class="titulos">
			<td class="local_pagto">Local de pagamento</td>
			<td class="vencimento2">Vencimento</td>
		</tr>
		<tr class="campos">
			<td class="local_pagto">QUALQUER BANCO ATÉ O VENCIMENTO</td>
			<td class="vencimento2"><?php echo $data_vencimento ?></td>
		</tr>
		</tbody>
		</table>
		
		<table class="line" cellspacing="0" cellpadding="0">
		<tbody>
		<tr class="titulos">
			<td class="cedente2">Cedente</td>
			<td class="ag_cod_cedente2">Agência/Código cedente</td>
		</tr>
		<tr class="campos">
			<td class="cedente2"><?php echo $cedente; ?></td>
			<td class="ag_cod_cedente2"><?php echo $agencia_codigo_cedente ?></td>
		</tr>
		</tbody>
		</table>

		<table class="line" cellspacing="0" cellpadding="0">
		<tbody>
		<tr class="titulos">
			<td class="data_doc">Data do documento</td>
			<td class="num_doc2">Nº documento</td>
			<td class="especie_doc">Espécie doc.</td>
			<td class="aceite">Aceite</td>
			<td class="data_process">Data process.</td>
			<td class="nosso_numero2">Nosso número</td>
		</tr>
		<tr class="campos">
			<td class="data_doc"><?php echo $data_documento ?></td>
			<td class="num_doc2"><?php echo $numero_documento ?></td>
			<td class="especie_doc"><?php echo $especie_doc ?></td>
			<td class="aceite"><?php echo $aceite ?></td>
			<td class="data_process"><?php echo $data_processamento ?></td>
			<td class="nosso_numero2"><?php echo $nosso_numero ?></td>
		</tr>
		</tbody>
		</table>

		<table class="line" cellspacing="0" cellpadding="0">
		<tbody>
		<tr class="titulos">
			<td class="reservado">Uso do  banco</td>
			<td class="carteira">Carteira</td>
			<td class="especie2">Espécie</td>
			<td class="qtd2">Quantidade</td>
			<td class="xvalor">x Valor</td>
			<td class="valor_doc2">(=) Valor documento</td>
		</tr>
		<tr class="campos">
			<td class="reservado">&nbsp;</td>
			<td class="carteira"><?php echo $carteira ?></td>
			<td class="especie2"><?php echo $especie?></td>
			<td class="qtd2"><?php echo $quantidade?></td</td>
			<td class="xvalor"><?php echo $valor_unitario ?></td>
			<td class="valor_doc2"><?php echo $valor_documento ?></td>
		</tr>
		</tbody>
		</table>
		
		
		<table class="line" cellspacing="0" cellpadding="0">
		<tbody>
		<tr><td class="last_line" rowspan="6">
			<table class="line" cellspacing="0" cellpadding="0">
			<tbody>
			<tr class="titulos">
				<td class="instrucoes">
						Instruções (Texto de responsabilidade do cedente)
				</td>
			</tr>
			<tr class="campos">
				<td class="instrucoes" rowspan="5">
                                    <div class="conteudo"><?php echo $instrucoes[0]; ?></div>
                                    <div class="conteudo"><?php echo $instrucoes[1]; ?></div>
				</td>
			</tr>
			</tbody>
			</table>
		</td></tr>
		
		<tr><td>
			<table class="line" cellspacing="0" cellpadding="0">
			<tbody>
			<tr class="titulos">
				<td class="desconto2">(-) Desconto / Abatimento</td>
			</tr>
			<tr class="campos">
				<td class="desconto2"><?php echo $desconto_abatimento ?></td>
			</tr>
			</tbody>
			</table>
		</td></tr>
		
		<tr><td>
			<table class="line" cellspacing="0" cellpadding="0">
			<tbody>
			<tr class="titulos">
				<td class="outras_deducoes2">(-) Outras deduções</td>
			</tr>
			<tr class="campos">
				<td class="outras_deducoes2"><?php echo $outras_deducoes ?></td>
			</tr>
			</tbody>
			</table>
		</td></tr>

		<tr><td>
			<table class="line" cellspacing="0" cellpadding="0">
			<tbody>
			<tr class="titulos">
				<td class="mora_multa2">(+) Mora / Multa</td>
			</tr>
			<tr class="campos">
				<td class="mora_multa2"><?php echo $mora_multa ?></td>
			</tr>
			</tbody>
			</table>
		</td></tr>

		<tr><td>
			<table class="line" cellspacing="0" cellpadding="0">
			<tbody>
			<tr class="titulos">
				<td class="outros_acrescimos2">(+) Outros Acréscimos</td>
			</tr>
			<tr class="campos">
				<td class="outros_acrescimos2"><?php echo $outros_acrescimos ?></td>
			</tr>
			</tbody>
			</table>
		</td></tr>

		<tr><td class="last_line">
			<table class="line" cellspacing="0" cellpadding="0">
			<tbody>
			<tr class="titulos">
				<td class="valor_cobrado2">(=) Valor cobrado</td>
			</tr>
			<tr class="campos">
				<td class="valor_cobrado2" align="right"><strong><?php echo $valor_cobrado ?></strong></td>
			</tr>
			</tbody>
			</table>
		</td></tr>
		</tbody>
		</table>
		
		
		<table class="line" cellspacing="0" cellpadding="0">
		<tbody>
		<tr class="titulos">
			<td class="sacado2">Sacado</td>
		</tr>
		<tr class="campos">
			<td class="sacado2">
				<p><strong><?php echo $sacado ?></strong></p>
				<p><?php echo $sacado_endereco1 ?> </p>
				<p><?php echo $sacado_endereco2 ?></p>
			</td>
		</tr>
		</tbody>
		</table>		
		
		<table class="line" cellspacing="0" cellpadding="0">
		<tbody>
		<tr class="titulos">
			<td class="sacador_avalista" colspan="2">Sacador/Avalista</td>
		</tr>
		<tr class="campos">
			<td class="sacador_avalista"><?php echo $sacador_avalista; ?></td>
			<td class="cod_baixa">Cód. baixa</td>
		</tr>
		</tbody>
		</table>
            
                <table class="line" cellspacing="0" cellpadding="0">
		<tbody>
		<tr align="right">
			<div align="right" class="footer">Autenticação mecânica - Ficha de Compensação</div>
		</tr>
		</tbody>
		</table>
            
                <table class="table-boleto" cellpadding="0" cellspacing="0" border="0">
                    <tbody>                        
                        <tr>
                            <td colspan="8" style="border: none">
                                <?php echo $codigo_barras ?>
                            </td>
                        </tr>
                    </tbody>    
                </table>
            
                <div class="cut">
			<p>Corte na linha pontilhada</p>
		</div>
        </div>
<div style="width: 666px">
        

        
        
    </div>
</div>
</body>
</html>
